"""The unified schema: 36 tables, 5 views, 2 triggers.

Revision ID: 0001
Revises:
Create Date: 2026-09-25

Three things in here are not ordinary autogenerated output, and each exists for a
reason the schema alone would not show:

1. **A bootstrap `ingest_run` row is inserted before anything else can need one.**
   Every PROJECTION table carries a `NOT NULL` `ingest_run_id`, and the plan's
   probe of this schema failed precisely there: seed rows pointing at a run that
   did not exist, which passes silently with SQLite's default `foreign_keys = off`
   and fails the moment they are enforced. `examkb/db.py` enforces them on every
   connection, so the row that makes a hand-written or seeded projection row legal
   is created here, in the migration that creates the constraint.

2. **The five views and two triggers are created and dropped here**, as replaceable
   objects. `examkb/models/views.py` describes their shape for querying; this file
   owns their SQL, so changing one is a migration rather than an edit that silently
   disagrees with what is in the database.

3. **No CHECK anywhere asserts that blueprint weights sum to 100.** AZ-104's ranges
   bound to 80/105 and SnowPro COF-C02's to 80/110 -- both correct transcriptions of
   correct documents. `blueprint.weights_sum_to_100` records the fact instead.

`UTCDateTime` (a TypeDecorator over `DateTime`) is spelled `sa.DateTime()` below:
at DDL level they are the same `DATETIME`, and a migration that imports application
code is a migration that breaks when that code moves.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# --------------------------------------------------------------------------------- views
#
# Derived state that must have exactly one definition. `verification` is the one the
# plan is most explicit about: computed from `verification_event` plus open disputes
# with fixed precedence, never a mutable column a re-run can overwrite behind you.

VIEWS: tuple[tuple[str, str], ...] = (
    (
        "question_verification",
        """
        CREATE VIEW question_verification AS
        SELECT question.id AS question_id,
               CASE
                   WHEN EXISTS (SELECT 1 FROM verification_event event
                                WHERE event.question_id = question.id
                                  AND event.level = 'known_bad') THEN 'known_bad'
                   WHEN EXISTS (SELECT 1 FROM dispute
                                WHERE dispute.question_id = question.id
                                  AND dispute.state = 'open') THEN 'disputed'
                   WHEN EXISTS (SELECT 1 FROM verification_event event
                                WHERE event.question_id = question.id
                                  AND event.level = 'human_reviewed') THEN 'human_reviewed'
                   WHEN EXISTS (SELECT 1 FROM verification_event event
                                WHERE event.question_id = question.id
                                  AND event.level = 'ai_reviewed') THEN 'ai_reviewed'
                   ELSE 'unverified'
               END AS verification
        FROM question
        """,
    ),
    (
        # An override corrects the key for *future* grading only. Past grades are
        # history; changing one is an explicit regrade (040), never a side effect.
        "current_answer_key",
        """
        CREATE VIEW current_answer_key AS
        SELECT question.id AS question_id,
               COALESCE(override.correct_labels, question.correct_labels) AS correct_labels,
               override.id AS override_id,
               CASE WHEN override.id IS NULL THEN 0 ELSE 1 END AS is_override
        FROM question
        LEFT JOIN override ON override.id = (
            SELECT in_force.id FROM override AS in_force
            WHERE in_force.question_id = question.id
              AND in_force.retired_at IS NULL
            ORDER BY in_force.effective_from DESC, in_force.id DESC
            LIMIT 1
        )
        """,
    ),
    (
        # Marks are append-only so the history survives; this is the latest one.
        "current_mark",
        """
        CREATE VIEW current_mark AS
        SELECT mark.question_id AS question_id,
               mark.value AS value,
               mark.created_at AS marked_at
        FROM mark
        WHERE mark.id = (
            SELECT latest.id FROM mark AS latest
            WHERE latest.question_id = mark.question_id
            ORDER BY latest.created_at DESC, latest.id DESC
            LIMIT 1
        )
        """,
    ),
    (
        "attempt_score",
        """
        CREATE VIEW attempt_score AS
        SELECT attempt.id AS attempt_id,
               attempt.certification_id AS certification_id,
               attempt.started_at AS started_at,
               attempt.submitted_at AS submitted_at,
               count(item.id) AS item_count,
               sum(CASE WHEN item.answered_at IS NOT NULL THEN 1 ELSE 0 END) AS answered_count,
               sum(CASE WHEN item.is_correct THEN 1 ELSE 0 END) AS correct_count,
               sum(COALESCE(item.credit, 0.0)) AS credit_total
        FROM attempt
        LEFT JOIN attempt_item AS item ON item.attempt_id = attempt.id
        GROUP BY attempt.id
        """,
    ),
    (
        # "First exposure" is defined once, here. A re-seen question is not a fresh
        # observation of the same knowledge, and an abandoned attempt never counts.
        "first_exposure_response",
        """
        CREATE VIEW first_exposure_response AS
        SELECT item.id AS attempt_item_id,
               item.attempt_id AS attempt_id,
               item.question_id AS question_id,
               item.blueprint_node_id AS blueprint_node_id,
               item.is_correct AS is_correct,
               item.credit AS credit,
               item.answered_at AS answered_at
        FROM attempt_item AS item
        JOIN attempt ON attempt.id = item.attempt_id
        WHERE attempt.submitted_at IS NOT NULL
          AND attempt.abandoned_at IS NULL
          AND item.answered_at IS NOT NULL
          AND item.id = (
              SELECT earliest.id FROM attempt_item AS earliest
              JOIN attempt AS earliest_attempt ON earliest_attempt.id = earliest.attempt_id
              WHERE earliest.question_id = item.question_id
                AND earliest.answered_at IS NOT NULL
                AND earliest_attempt.submitted_at IS NOT NULL
                AND earliest_attempt.abandoned_at IS NULL
              ORDER BY earliest.answered_at ASC, earliest.id ASC
              LIMIT 1
          )
        """,
    ),
)


# ------------------------------------------------------------------------------ triggers
#
# Both defend an invariant the service layer must not be the only thing enforcing,
# and both are asserted against SQLite directly by their owning issues (013, 041).

TRIGGERS: tuple[tuple[str, str], ...] = (
    (
        # What the user saw is frozen the moment they answer it. Without this, a
        # corpus rebuild or a key override could rewrite the exam that was sat, and
        # every past score would quietly stop being explainable.
        "attempt_item_snapshot_is_immutable",
        """
        CREATE TRIGGER attempt_item_snapshot_is_immutable
        BEFORE UPDATE OF snapshot_json, option_order ON attempt_item
        FOR EACH ROW WHEN OLD.answered_at IS NOT NULL
        BEGIN
            SELECT RAISE(ABORT,
                'attempt_item.snapshot_json is immutable once the item is answered');
        END
        """,
    ),
    (
        # Keyed on the question, not on the thread's shape: otherwise the obvious
        # hole stays open -- start an attempt, then ask about one of its questions
        # from /browse. `submitted_at IS NULL` is the single definition of "open".
        "chat_thread_requires_no_open_attempt",
        """
        CREATE TRIGGER chat_thread_requires_no_open_attempt
        BEFORE INSERT ON chat_thread
        FOR EACH ROW WHEN EXISTS (
            SELECT 1 FROM attempt_item AS item
            JOIN attempt ON attempt.id = item.attempt_id
            WHERE item.question_id = NEW.question_id
              AND attempt.submitted_at IS NULL
        )
        BEGIN
            SELECT RAISE(ABORT,
                'chat is closed while an attempt containing this question is open');
        END
        """,
    ),
)


# ----------------------------------------------------------------------------- bootstrap
#
# Row zero. Dated at the epoch so `ORDER BY started_at` puts it before every real
# run, and so applying this migration twice produces the same bytes both times.

BOOTSTRAP_INGEST_RUN = """
INSERT INTO ingest_run
    (id, started_at, finished_at, mode, status, kb_fingerprint,
     shard_count, question_count, examkb_version, note)
VALUES
    ('bootstrap', '1970-01-01 00:00:00.000000', '1970-01-01 00:00:00.000000',
     'bootstrap', 'bootstrap', NULL, 0, 0, NULL,
     'Created by 0001_initial so a projection row can exist before the first ingest run.')
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certification_id', sa.Text(), nullable=False),
    sa.Column('exam_id', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('abandoned_at', sa.DateTime(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=True),
    sa.Column('sampler_json', sa.JSON(), nullable=True),
    sa.Column('weight_source', sa.Text(), nullable=True),
    sa.Column('apportionment_json', sa.JSON(), nullable=True),
    sa.Column('format_profile_json', sa.JSON(), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('credit_total', sa.Float(), nullable=True),
    sa.Column('scaled_score', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt'))
    )
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.create_index('ix_attempt_certification_id_started_at', ['certification_id', 'started_at'], unique=False)
        batch_op.create_index('ix_attempt_submitted_at', ['submitted_at'], unique=False)

    op.create_table('dispute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('attempt_item_id', sa.Integer(), nullable=True),
    sa.Column('chat_thread_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('claim_md', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_md', sa.Text(), nullable=True),
    sa.CheckConstraint("state IN ('open', 'accepted', 'rejected')", name=op.f('ck_dispute_state_known')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispute'))
    )
    with op.batch_alter_table('dispute', schema=None) as batch_op:
        batch_op.create_index('ix_dispute_attempt_item_id', ['attempt_item_id'], unique=False)
        batch_op.create_index('ix_dispute_question_id_state', ['question_id', 'state'], unique=False)
        batch_op.create_index('ix_dispute_state', ['state'], unique=False)

    op.create_table('ingest_run',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('kb_fingerprint', sa.Text(), nullable=True),
    sa.Column('shard_count', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('examkb_version', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("mode IN ('bootstrap', 'incremental', 'rebuild')", name=op.f('ck_ingest_run_mode_known')),
    sa.CheckConstraint("status IN ('bootstrap', 'running', 'ok', 'failed')", name=op.f('ck_ingest_run_status_known')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_run'))
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('checkpoint_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('claimed_by', sa.Text(), nullable=True),
    sa.Column('resume_command', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("state IN ('queued', 'running', 'done', 'failed', 'interrupted', 'cancelled')", name=op.f('ck_job_state_known')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('ix_job_kind', ['kind'], unique=False)
        batch_op.create_index('ix_job_state_created_at', ['state', 'created_at'], unique=False)

    op.create_table('mark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source IN ('ui', 'import')", name=op.f('ck_mark_source_known')),
    sa.CheckConstraint("value IN ('known', 'unsure', 'flagged', 'cleared')", name=op.f('ck_mark_value_known')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mark'))
    )
    with op.batch_alter_table('mark', schema=None) as batch_op:
        batch_op.create_index('ix_mark_question_id_created_at', ['question_id', 'created_at'], unique=False)

    op.create_table('certification',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('vendor', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('ingest_run_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_certification_ingest_run_id_ingest_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certification'))
    )
    with op.batch_alter_table('certification', schema=None) as batch_op:
        batch_op.create_index('ix_certification_vendor', ['vendor'], unique=False)

    op.create_table('generation_run',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('certification_id', sa.Text(), nullable=False),
    sa.Column('blueprint_id', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('grounding_json', sa.JSON(), nullable=True),
    sa.Column('degraded_exemplar_mode', sa.Boolean(), nullable=False),
    sa.Column('exemplar_certification_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_generation_run_job_id_job')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_run'))
    )
    with op.batch_alter_table('generation_run', schema=None) as batch_op:
        batch_op.create_index('ix_generation_run_certification_id', ['certification_id'], unique=False)
        batch_op.create_index('ix_generation_run_job_id', ['job_id'], unique=False)

    op.create_table('job_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("state IN ('pending', 'running', 'done', 'failed', 'skipped')", name=op.f('ck_job_item_state_known')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_job_item_job_id_job'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_item')),
    sa.UniqueConstraint('job_id', 'item_key', name='uq_job_item_job_id_item_key')
    )
    with op.batch_alter_table('job_item', schema=None) as batch_op:
        batch_op.create_index('ix_job_item_job_id_state', ['job_id', 'state'], unique=False)

    op.create_table('llm_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('subject_type', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Text(), nullable=True),
    sa.Column('prompt_sha256', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('semaphore_limit', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('ok', 'error', 'timeout', 'refused')", name=op.f('ck_llm_call_outcome_known')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_llm_call_job_id_job')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_call'))
    )
    with op.batch_alter_table('llm_call', schema=None) as batch_op:
        batch_op.create_index('ix_llm_call_job_id', ['job_id'], unique=False)
        batch_op.create_index('ix_llm_call_outcome', ['outcome'], unique=False)
        batch_op.create_index('ix_llm_call_purpose_started_at', ['purpose', 'started_at'], unique=False)
        batch_op.create_index('ix_llm_call_subject_type_subject_id', ['subject_type', 'subject_id'], unique=False)

    op.create_table('override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('dispute_id', sa.Integer(), nullable=True),
    sa.Column('correct_labels', sa.JSON(), nullable=False),
    sa.Column('reason_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dispute_id'], ['dispute.id'], name=op.f('fk_override_dispute_id_dispute')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_override'))
    )
    with op.batch_alter_table('override', schema=None) as batch_op:
        batch_op.create_index('ix_override_question_id_retired_at', ['question_id', 'retired_at'], unique=False)

    op.create_table('reference',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('display_url', sa.Text(), nullable=False),
    sa.Column('host', sa.Text(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('ingest_run_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_reference_ingest_run_id_ingest_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference'))
    )
    with op.batch_alter_table('reference', schema=None) as batch_op:
        batch_op.create_index('ix_reference_host', ['host'], unique=False)

    op.create_table('shard',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('ingest_run_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_shard_ingest_run_id_ingest_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shard'))
    )
    with op.batch_alter_table('shard', schema=None) as batch_op:
        batch_op.create_index('ix_shard_ingest_run_id', ['ingest_run_id'], unique=False)

    op.create_table('attempt_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('blueprint_node_id', sa.Text(), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('option_order', sa.JSON(), nullable=False),
    sa.Column('selected_labels', sa.JSON(), nullable=True),
    sa.Column('first_shown_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('time_ms', sa.Integer(), nullable=False),
    sa.Column('change_count', sa.Integer(), nullable=False),
    sa.Column('seen_ordinal', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('graded_key', sa.JSON(), nullable=True),
    sa.Column('override_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], name=op.f('fk_attempt_item_attempt_id_attempt'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['override_id'], ['override.id'], name=op.f('fk_attempt_item_override_id_override')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt_item')),
    sa.UniqueConstraint('attempt_id', 'position', name='uq_attempt_item_attempt_id_position')
    )
    with op.batch_alter_table('attempt_item', schema=None) as batch_op:
        batch_op.create_index('ix_attempt_item_answered_at', ['answered_at'], unique=False)
        batch_op.create_index('ix_attempt_item_attempt_id', ['attempt_id'], unique=False)
        batch_op.create_index('ix_attempt_item_blueprint_node_id', ['blueprint_node_id'], unique=False)
        batch_op.create_index('ix_attempt_item_question_id', ['question_id'], unique=False)

    op.create_table('blueprint',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('certification_id', sa.Text(), nullable=False),
    sa.Column('vendor', sa.Text(), nullable=False),
    sa.Column('version_label', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Text(), nullable=True),
    sa.Column('weight_regime', sa.Text(), nullable=False),
    sa.Column('weights_sum', sa.Float(), nullable=True),
    sa.Column('weights_sum_to_100', sa.Boolean(), nullable=True),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('ingest_run_id', sa.Text(), nullable=False),
    sa.CheckConstraint("weight_regime IN ('exact', 'range', 'absent', 'unpublished')", name=op.f('ck_blueprint_weight_regime_known')),
    sa.CheckConstraint('max_depth BETWEEN 1 AND 4', name=op.f('ck_blueprint_max_depth_in_range')),
    sa.ForeignKeyConstraint(['certification_id'], ['certification.id'], name=op.f('fk_blueprint_certification_id_certification')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_blueprint_ingest_run_id_ingest_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blueprint'))
    )
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.create_index('ix_blueprint_certification_id', ['certification_id'], unique=False)

    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_run_id', sa.Text(), nullable=False),
    sa.Column('blueprint_node_id', sa.Text(), nullable=True),
    sa.Column('llm_call_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('select_count', sa.Integer(), nullable=False),
    sa.Column('prompt_md', sa.Text(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('correct_labels', sa.JSON(), nullable=False),
    sa.Column('overall_explanation_md', sa.Text(), nullable=True),
    sa.Column('prompt_sha256', sa.Text(), nullable=True),
    sa.Column('normalized_sha256', sa.Text(), nullable=True),
    sa.Column('item_sha256', sa.Text(), nullable=True),
    sa.Column('dedup_max_score', sa.Float(), nullable=True),
    sa.Column('dedup_nearest_question_id', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('published_question_id', sa.Text(), nullable=True),
    sa.Column('published_path', sa.Text(), nullable=True),
    sa.CheckConstraint("state IN ('draft', 'queued', 'approved', 'rejected', 'superseded')", name=op.f('ck_candidate_state_known')),
    sa.ForeignKeyConstraint(['generation_run_id'], ['generation_run.id'], name=op.f('fk_candidate_generation_run_id_generation_run'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_call.id'], name=op.f('fk_candidate_llm_call_id_llm_call')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate'))
    )
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.create_index('ix_candidate_generation_run_id', ['generation_run_id'], unique=False)
        batch_op.create_index('ix_candidate_normalized_sha256', ['normalized_sha256'], unique=False)
        batch_op.create_index('ix_candidate_state_created_at', ['state', 'created_at'], unique=False)

    op.create_table('domain',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('certification_id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('ingest_run_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certification.id'], name=op.f('fk_domain_certification_id_certification')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_domain_ingest_run_id_ingest_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain')),
    sa.UniqueConstraint('certification_id', 'label', name='uq_domain_certification_id_label')
    )
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.create_index('ix_domain_certification_id', ['certification_id'], unique=False)

    op.create_table('exam',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('certification_id', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('ingest_run_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certification.id'], name=op.f('fk_exam_certification_id_certification')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_exam_ingest_run_id_ingest_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam')),
    sa.UniqueConstraint('certification_id', 'slug', name='uq_exam_certification_id_slug')
    )
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.create_index('ix_exam_certification_id', ['certification_id'], unique=False)
        batch_op.create_index('ix_exam_mode', ['mode'], unique=False)

    op.create_table('format_profile',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('certification_id', sa.Text(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('scale_min', sa.Integer(), nullable=True),
    sa.Column('scale_max', sa.Integer(), nullable=True),
    sa.Column('cut_score', sa.Integer(), nullable=True),
    sa.Column('validity_months', sa.Integer(), nullable=True),
    sa.Column('allowed_formats', sa.JSON(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certification.id'], name=op.f('fk_format_profile_certification_id_certification')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_format_profile_ingest_run_id_ingest_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_format_profile')),
    sa.UniqueConstraint('certification_id', name='uq_format_profile_certification_id')
    )
    op.create_table('regrade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('override_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('original_correct_count', sa.Integer(), nullable=True),
    sa.Column('original_credit_total', sa.Float(), nullable=True),
    sa.Column('original_scaled_score', sa.Integer(), nullable=True),
    sa.Column('new_correct_count', sa.Integer(), nullable=True),
    sa.Column('new_credit_total', sa.Float(), nullable=True),
    sa.Column('new_scaled_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], name=op.f('fk_regrade_attempt_id_attempt'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['override_id'], ['override.id'], name=op.f('fk_regrade_override_id_override')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regrade'))
    )
    with op.batch_alter_table('regrade', schema=None) as batch_op:
        batch_op.create_index('ix_regrade_attempt_id', ['attempt_id'], unique=False)

    op.create_table('taxon_proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('blocked_by_taxon_id', sa.Text(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('llm_call_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_note', sa.Text(), nullable=True),
    sa.CheckConstraint("state IN ('proposed', 'accepted', 'rejected')", name=op.f('ck_taxon_proposal_state_known')),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_call.id'], name=op.f('fk_taxon_proposal_llm_call_id_llm_call')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taxon_proposal'))
    )
    with op.batch_alter_table('taxon_proposal', schema=None) as batch_op:
        batch_op.create_index('ix_taxon_proposal_state_created_at', ['state', 'created_at'], unique=False)

    op.create_table('taxon_scheme',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('certification_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('cardinality', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.Text(), nullable=False),
    sa.CheckConstraint("cardinality IN ('one', 'many')", name=op.f('ck_taxon_scheme_cardinality_known')),
    sa.ForeignKeyConstraint(['certification_id'], ['certification.id'], name=op.f('fk_taxon_scheme_certification_id_certification')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_taxon_scheme_ingest_run_id_ingest_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taxon_scheme'))
    )
    with op.batch_alter_table('taxon_scheme', schema=None) as batch_op:
        batch_op.create_index('ix_taxon_scheme_certification_id', ['certification_id'], unique=False)

    op.create_table('blueprint_node',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('blueprint_id', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('weight_pct', sa.Float(), nullable=True),
    sa.Column('weight_min', sa.Float(), nullable=True),
    sa.Column('weight_max', sa.Float(), nullable=True),
    sa.CheckConstraint('depth BETWEEN 1 AND 4', name=op.f('ck_blueprint_node_depth_in_range')),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprint.id'], name=op.f('fk_blueprint_node_blueprint_id_blueprint'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['blueprint_node.id'], name=op.f('fk_blueprint_node_parent_id_blueprint_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blueprint_node')),
    sa.UniqueConstraint('blueprint_id', 'path', name='uq_blueprint_node_blueprint_id_path')
    )
    with op.batch_alter_table('blueprint_node', schema=None) as batch_op:
        batch_op.create_index('ix_blueprint_node_blueprint_id', ['blueprint_id'], unique=False)
        batch_op.create_index('ix_blueprint_node_blueprint_id_depth', ['blueprint_id', 'depth'], unique=False)
        batch_op.create_index('ix_blueprint_node_parent_id', ['parent_id'], unique=False)

    op.create_table('blueprint_source',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('blueprint_id', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('retrieved_on', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprint.id'], name=op.f('fk_blueprint_source_blueprint_id_blueprint'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blueprint_source'))
    )
    with op.batch_alter_table('blueprint_source', schema=None) as batch_op:
        batch_op.create_index('ix_blueprint_source_blueprint_id', ['blueprint_id'], unique=False)

    op.create_table('candidate_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('edited_json', sa.JSON(), nullable=True),
    sa.Column('undoes_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action IN ('approve', 'reject', 'edit', 'skip', 'undo')", name=op.f('ck_candidate_decision_action_known')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], name=op.f('fk_candidate_decision_candidate_id_candidate'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['undoes_id'], ['candidate_decision.id'], name=op.f('fk_candidate_decision_undoes_id_candidate_decision')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_decision'))
    )
    with op.batch_alter_table('candidate_decision', schema=None) as batch_op:
        batch_op.create_index('ix_candidate_decision_candidate_id_created_at', ['candidate_id', 'created_at'], unique=False)

    op.create_table('candidate_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('voter_index', sa.Integer(), nullable=False),
    sa.Column('llm_call_id', sa.Integer(), nullable=True),
    sa.Column('chosen_labels', sa.JSON(), nullable=True),
    sa.Column('agrees_with_key', sa.Boolean(), nullable=True),
    sa.Column('rationale_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], name=op.f('fk_candidate_review_candidate_id_candidate'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_call.id'], name=op.f('fk_candidate_review_llm_call_id_llm_call')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_review')),
    sa.UniqueConstraint('candidate_id', 'voter_index', name='uq_candidate_review_candidate_id_voter_index')
    )
    with op.batch_alter_table('candidate_review', schema=None) as batch_op:
        batch_op.create_index('ix_candidate_review_candidate_id', ['candidate_id'], unique=False)

    op.create_table('chat_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('attempt_item_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("scope IN ('results', 'browse')", name=op.f('ck_chat_thread_scope_known')),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], name=op.f('fk_chat_thread_attempt_id_attempt')),
    sa.ForeignKeyConstraint(['attempt_item_id'], ['attempt_item.id'], name=op.f('fk_chat_thread_attempt_item_id_attempt_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_thread'))
    )
    with op.batch_alter_table('chat_thread', schema=None) as batch_op:
        batch_op.create_index('ix_chat_thread_attempt_id', ['attempt_id'], unique=False)
        batch_op.create_index('ix_chat_thread_question_id', ['question_id'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('certification_id', sa.Text(), nullable=False),
    sa.Column('exam_id', sa.Text(), nullable=True),
    sa.Column('domain_id', sa.Text(), nullable=True),
    sa.Column('domain_label', sa.Text(), nullable=True),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('select_count', sa.Integer(), nullable=False),
    sa.Column('prompt_md', sa.Text(), nullable=False),
    sa.Column('overall_explanation_md', sa.Text(), nullable=True),
    sa.Column('correct_labels', sa.JSON(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('source_provider', sa.Text(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_course_url', sa.Text(), nullable=True),
    sa.Column('shard_id', sa.Text(), nullable=True),
    sa.Column('prompt_sha256', sa.Text(), nullable=True),
    sa.Column('normalized_sha256', sa.Text(), nullable=True),
    sa.Column('item_sha256', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.Text(), nullable=False),
    sa.CheckConstraint("origin IN ('vendor_dump', 'official_sample', 'local_generation', 'hand_written')", name=op.f('ck_question_origin_known')),
    sa.CheckConstraint("type IN ('single_select', 'multi_select')", name=op.f('ck_question_type_known')),
    sa.CheckConstraint('select_count >= 1', name=op.f('ck_question_select_count_positive')),
    sa.ForeignKeyConstraint(['certification_id'], ['certification.id'], name=op.f('fk_question_certification_id_certification')),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], name=op.f('fk_question_domain_id_domain')),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('fk_question_exam_id_exam')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_question_ingest_run_id_ingest_run')),
    sa.ForeignKeyConstraint(['shard_id'], ['shard.id'], name=op.f('fk_question_shard_id_shard')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index('ix_question_certification_id', ['certification_id'], unique=False)
        batch_op.create_index('ix_question_content_hash', ['content_hash'], unique=False)
        batch_op.create_index('ix_question_domain_id', ['domain_id'], unique=False)
        batch_op.create_index('ix_question_exam_id', ['exam_id'], unique=False)
        batch_op.create_index('ix_question_ingest_run_id', ['ingest_run_id'], unique=False)
        batch_op.create_index('ix_question_item_sha256', ['item_sha256'], unique=False)
        batch_op.create_index('ix_question_normalized_sha256', ['normalized_sha256'], unique=False)
        batch_op.create_index('ix_question_origin', ['origin'], unique=False)
        batch_op.create_index('ix_question_prompt_sha256', ['prompt_sha256'], unique=False)
        batch_op.create_index('ix_question_type', ['type'], unique=False)

    op.create_table('regrade_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regrade_id', sa.Integer(), nullable=False),
    sa.Column('attempt_item_id', sa.Integer(), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('now_correct', sa.Boolean(), nullable=True),
    sa.Column('was_credit', sa.Float(), nullable=True),
    sa.Column('now_credit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_item_id'], ['attempt_item.id'], name=op.f('fk_regrade_item_attempt_item_id_attempt_item')),
    sa.ForeignKeyConstraint(['regrade_id'], ['regrade.id'], name=op.f('fk_regrade_item_regrade_id_regrade'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regrade_item')),
    sa.UniqueConstraint('regrade_id', 'attempt_item_id', name='uq_regrade_item_regrade_id_attempt_item_id')
    )
    with op.batch_alter_table('regrade_item', schema=None) as batch_op:
        batch_op.create_index('ix_regrade_item_regrade_id', ['regrade_id'], unique=False)

    op.create_table('verification_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('note_md', sa.Text(), nullable=True),
    sa.Column('llm_call_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("level IN ('unverified', 'ai_reviewed', 'human_reviewed', 'known_bad')", name=op.f('ck_verification_event_level_known')),
    sa.CheckConstraint("source IN ('ai_review', 'human', 'import')", name=op.f('ck_verification_event_source_known')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], name=op.f('fk_verification_event_candidate_id_candidate')),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_call.id'], name=op.f('fk_verification_event_llm_call_id_llm_call')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_event'))
    )
    with op.batch_alter_table('verification_event', schema=None) as batch_op:
        batch_op.create_index('ix_verification_event_level', ['level'], unique=False)
        batch_op.create_index('ix_verification_event_question_id_created_at', ['question_id', 'created_at'], unique=False)

    op.create_table('blueprint_domain_map',
    sa.Column('domain_id', sa.Text(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=False),
    sa.Column('join_method', sa.Text(), nullable=False),
    sa.CheckConstraint("join_method IN ('exact')", name=op.f('ck_blueprint_domain_map_join_method_known')),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], name=op.f('fk_blueprint_domain_map_domain_id_domain')),
    sa.ForeignKeyConstraint(['node_id'], ['blueprint_node.id'], name=op.f('fk_blueprint_domain_map_node_id_blueprint_node'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('domain_id', 'node_id', name='pk_blueprint_domain_map')
    )
    with op.batch_alter_table('blueprint_domain_map', schema=None) as batch_op:
        batch_op.create_index('ix_blueprint_domain_map_node_id', ['node_id'], unique=False)

    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('finish_reason', sa.Text(), nullable=True),
    sa.Column('llm_call_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name=op.f('ck_chat_message_role_known')),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_call.id'], name=op.f('fk_chat_message_llm_call_id_llm_call')),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_thread.id'], name=op.f('fk_chat_message_thread_id_chat_thread'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index('ix_chat_message_thread_id_created_at', ['thread_id', 'created_at'], unique=False)

    op.create_table('question_annotation',
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('difficulty_band', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('annotation_run_id', sa.Text(), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.Text(), nullable=False),
    sa.CheckConstraint("source IS NULL OR source IN ('seed', 'model', 'human')", name=op.f('ck_question_annotation_source_known')),
    sa.CheckConstraint('difficulty_band IS NULL OR difficulty_band BETWEEN 1 AND 5', name=op.f('ck_question_annotation_difficulty_band_in_range')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_question_annotation_ingest_run_id_ingest_run')),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_question_annotation_question_id_question'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', name=op.f('pk_question_annotation'))
    )
    op.create_table('question_option',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text_md', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('explanation_md', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_question_option_question_id_question'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_option')),
    sa.UniqueConstraint('question_id', 'label', name='uq_question_option_question_id_label')
    )
    with op.batch_alter_table('question_option', schema=None) as batch_op:
        batch_op.create_index('ix_question_option_question_id', ['question_id'], unique=False)

    op.create_table('question_reference',
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('raw_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_question_reference_question_id_question'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.id'], name=op.f('fk_question_reference_reference_id_reference')),
    sa.PrimaryKeyConstraint('question_id', 'reference_id', name='pk_question_reference')
    )
    with op.batch_alter_table('question_reference', schema=None) as batch_op:
        batch_op.create_index('ix_question_reference_reference_id', ['reference_id'], unique=False)

    op.create_table('taxon',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('scheme_id', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_taxon_ingest_run_id_ingest_run')),
    sa.ForeignKeyConstraint(['node_id'], ['blueprint_node.id'], name=op.f('fk_taxon_node_id_blueprint_node')),
    sa.ForeignKeyConstraint(['parent_id'], ['taxon.id'], name=op.f('fk_taxon_parent_id_taxon')),
    sa.ForeignKeyConstraint(['scheme_id'], ['taxon_scheme.id'], name=op.f('fk_taxon_scheme_id_taxon_scheme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taxon')),
    sa.UniqueConstraint('scheme_id', 'slug', name='uq_taxon_scheme_id_slug')
    )
    with op.batch_alter_table('taxon', schema=None) as batch_op:
        batch_op.create_index('ix_taxon_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('ix_taxon_scheme_id', ['scheme_id'], unique=False)

    op.create_table('question_taxon',
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('taxon_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('annotation_run_id', sa.Text(), nullable=True),
    sa.CheckConstraint("source IN ('seed', 'model', 'human')", name=op.f('ck_question_taxon_source_known')),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_question_taxon_question_id_question'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taxon_id'], ['taxon.id'], name=op.f('fk_question_taxon_taxon_id_taxon'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'taxon_id', name='pk_question_taxon')
    )
    with op.batch_alter_table('question_taxon', schema=None) as batch_op:
        batch_op.create_index('ix_question_taxon_taxon_id', ['taxon_id'], unique=False)

    # ### end Alembic commands ###

    for _name, sql in VIEWS:
        op.execute(sql)
    for _name, sql in TRIGGERS:
        op.execute(sql)
    op.execute(BOOTSTRAP_INGEST_RUN)


def downgrade() -> None:
    # Replaceable objects first: a view left over a dropped table is a view that
    # fails at query time rather than at migration time.
    for name, _sql in reversed(TRIGGERS):
        op.execute(f"DROP TRIGGER IF EXISTS {name}")
    for name, _sql in reversed(VIEWS):
        op.execute(f"DROP VIEW IF EXISTS {name}")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_taxon', schema=None) as batch_op:
        batch_op.drop_index('ix_question_taxon_taxon_id')

    op.drop_table('question_taxon')
    with op.batch_alter_table('taxon', schema=None) as batch_op:
        batch_op.drop_index('ix_taxon_scheme_id')
        batch_op.drop_index('ix_taxon_parent_id')

    op.drop_table('taxon')
    with op.batch_alter_table('question_reference', schema=None) as batch_op:
        batch_op.drop_index('ix_question_reference_reference_id')

    op.drop_table('question_reference')
    with op.batch_alter_table('question_option', schema=None) as batch_op:
        batch_op.drop_index('ix_question_option_question_id')

    op.drop_table('question_option')
    op.drop_table('question_annotation')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_message_thread_id_created_at')

    op.drop_table('chat_message')
    with op.batch_alter_table('blueprint_domain_map', schema=None) as batch_op:
        batch_op.drop_index('ix_blueprint_domain_map_node_id')

    op.drop_table('blueprint_domain_map')
    with op.batch_alter_table('verification_event', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_event_question_id_created_at')
        batch_op.drop_index('ix_verification_event_level')

    op.drop_table('verification_event')
    with op.batch_alter_table('regrade_item', schema=None) as batch_op:
        batch_op.drop_index('ix_regrade_item_regrade_id')

    op.drop_table('regrade_item')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index('ix_question_type')
        batch_op.drop_index('ix_question_prompt_sha256')
        batch_op.drop_index('ix_question_origin')
        batch_op.drop_index('ix_question_normalized_sha256')
        batch_op.drop_index('ix_question_item_sha256')
        batch_op.drop_index('ix_question_ingest_run_id')
        batch_op.drop_index('ix_question_exam_id')
        batch_op.drop_index('ix_question_domain_id')
        batch_op.drop_index('ix_question_content_hash')
        batch_op.drop_index('ix_question_certification_id')

    op.drop_table('question')
    with op.batch_alter_table('chat_thread', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_thread_question_id')
        batch_op.drop_index('ix_chat_thread_attempt_id')

    op.drop_table('chat_thread')
    with op.batch_alter_table('candidate_review', schema=None) as batch_op:
        batch_op.drop_index('ix_candidate_review_candidate_id')

    op.drop_table('candidate_review')
    with op.batch_alter_table('candidate_decision', schema=None) as batch_op:
        batch_op.drop_index('ix_candidate_decision_candidate_id_created_at')

    op.drop_table('candidate_decision')
    with op.batch_alter_table('blueprint_source', schema=None) as batch_op:
        batch_op.drop_index('ix_blueprint_source_blueprint_id')

    op.drop_table('blueprint_source')
    with op.batch_alter_table('blueprint_node', schema=None) as batch_op:
        batch_op.drop_index('ix_blueprint_node_parent_id')
        batch_op.drop_index('ix_blueprint_node_blueprint_id_depth')
        batch_op.drop_index('ix_blueprint_node_blueprint_id')

    op.drop_table('blueprint_node')
    with op.batch_alter_table('taxon_scheme', schema=None) as batch_op:
        batch_op.drop_index('ix_taxon_scheme_certification_id')

    op.drop_table('taxon_scheme')
    with op.batch_alter_table('taxon_proposal', schema=None) as batch_op:
        batch_op.drop_index('ix_taxon_proposal_state_created_at')

    op.drop_table('taxon_proposal')
    with op.batch_alter_table('regrade', schema=None) as batch_op:
        batch_op.drop_index('ix_regrade_attempt_id')

    op.drop_table('regrade')
    op.drop_table('format_profile')
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_index('ix_exam_mode')
        batch_op.drop_index('ix_exam_certification_id')

    op.drop_table('exam')
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_index('ix_domain_certification_id')

    op.drop_table('domain')
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_index('ix_candidate_state_created_at')
        batch_op.drop_index('ix_candidate_normalized_sha256')
        batch_op.drop_index('ix_candidate_generation_run_id')

    op.drop_table('candidate')
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.drop_index('ix_blueprint_certification_id')

    op.drop_table('blueprint')
    with op.batch_alter_table('attempt_item', schema=None) as batch_op:
        batch_op.drop_index('ix_attempt_item_question_id')
        batch_op.drop_index('ix_attempt_item_blueprint_node_id')
        batch_op.drop_index('ix_attempt_item_attempt_id')
        batch_op.drop_index('ix_attempt_item_answered_at')

    op.drop_table('attempt_item')
    with op.batch_alter_table('shard', schema=None) as batch_op:
        batch_op.drop_index('ix_shard_ingest_run_id')

    op.drop_table('shard')
    with op.batch_alter_table('reference', schema=None) as batch_op:
        batch_op.drop_index('ix_reference_host')

    op.drop_table('reference')
    with op.batch_alter_table('override', schema=None) as batch_op:
        batch_op.drop_index('ix_override_question_id_retired_at')

    op.drop_table('override')
    with op.batch_alter_table('llm_call', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_call_subject_type_subject_id')
        batch_op.drop_index('ix_llm_call_purpose_started_at')
        batch_op.drop_index('ix_llm_call_outcome')
        batch_op.drop_index('ix_llm_call_job_id')

    op.drop_table('llm_call')
    with op.batch_alter_table('job_item', schema=None) as batch_op:
        batch_op.drop_index('ix_job_item_job_id_state')

    op.drop_table('job_item')
    with op.batch_alter_table('generation_run', schema=None) as batch_op:
        batch_op.drop_index('ix_generation_run_job_id')
        batch_op.drop_index('ix_generation_run_certification_id')

    op.drop_table('generation_run')
    with op.batch_alter_table('certification', schema=None) as batch_op:
        batch_op.drop_index('ix_certification_vendor')

    op.drop_table('certification')
    with op.batch_alter_table('mark', schema=None) as batch_op:
        batch_op.drop_index('ix_mark_question_id_created_at')

    op.drop_table('mark')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('ix_job_state_created_at')
        batch_op.drop_index('ix_job_kind')

    op.drop_table('job')
    op.drop_table('ingest_run')
    with op.batch_alter_table('dispute', schema=None) as batch_op:
        batch_op.drop_index('ix_dispute_state')
        batch_op.drop_index('ix_dispute_question_id_state')
        batch_op.drop_index('ix_dispute_attempt_item_id')

    op.drop_table('dispute')
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_index('ix_attempt_submitted_at')
        batch_op.drop_index('ix_attempt_certification_id_started_at')

    op.drop_table('attempt')
    # ### end Alembic commands ###
